### ISSUE TITLE
How to download?

### ISSUE THREAD

**Issue by ZiliangMiao** [url-kaist/HeLiMOS-PointCloud-Toolbox#2]
Dear authors,

Thanks for your remarkable job! I've always believed that Semantic KITTI is far not enought as moving object segmentation benchmark. Your new benchmark with heterogeneous sensor data looks good. How can I download this dataset?

Best regards,
Ziliang

**Comment by LimHyungTae** [comment]
As we open-source the dataset, I'd like to close this issue. Thanks!
